### ISSUE TITLE
Can't install in OS X Yosemite

### ISSUE THREAD

**Issue by eddie129** [Superbil/protobuf-objc#2]
Enviroment : OS 10.10.1 with protobuf 2.6.0

**Comment by Superbil** [comment]
Is that problem to install by homebrew ?

**Comment by Superbil** [comment]
look like problem is install with protobuf 2.6.0, I will let it depends on 2.5.0

**Comment by Superbil** [comment]
I fixed it dde2c2daf1df03e9c7323e7961b0d333df884432

**Comment by Superbil** [comment]
If install protobuf before, use `brew rm protobuf` to remove old one.
